all:
	g++ -o blackjack.o blackjack/Game.cpp blackjack/Deck.cpp blackjack/House.cpp blackjack/Player.cpp blackjack/GenericPlayer.cpp blackjack/hand.cpp blackjack/card.cpp blackjack/blackjack.cpp 
	g++ overriding_boss.cpp -o oboss.o
	g++ polymorphic_bad_guy.cpp -o bad.o
	g++ simple_boss.cpp -o boss.o
	g++ simple_boss2.cpp -o boss2.o

