all:
	g++ give_me_a_number.cpp -o  give.o
	g++ global_reach.cpp -o global.o
	g++ instructions.cpp -o instructions.o
	g++ mad-lib.cpp -o madlibs.o
	g++ scoping.cpp -o scoping.o
	g++ taking_damage.cpp -o damage.o
	g++ triple.cpp -o triple.o
	g++ yes_or_no.cpp -o yesno.o
